### ISSUE TITLE
unnamed import is being shaken away with tree shaking

### ISSUE THREAD

**Issue by PieterSwitten** [stealjs/steal-tools#1078]
According to 'https://stealjs.com/docs/steal-tools.tree-shaking.html#preventing-code-removal' the `imports` without a variable should not be removed in the build by tree shaking.

When I do a import like `import './foobar.js'` It will removed after the build.
Inside `foobar.js` there is only one line with `console.log('foobar');`.

I have to explicit export something before it is not being removed in the build.
```
console.log('foobar');
export default {};
```
Then it does work after I have build.

Is this a bug in the tree shaking or is it the expected result and should we update our code?

**Comment by matthewp** [comment]
It's a bug, I thought I had a test for this though. Will check it out.

**Comment by frank-dspeed** [comment]
@matthewp as far as i know and would expect steal needs a config that this is a global module to don't get tree shaken away am i right maybe?

i come to this because i lately studied all existing implementations and i am sure i readed this.

Instead of disable tree shaking it is better to update your code to prevent needed side-effects from being removed. For example, you might have the following code:

import thing from "~/thing";

Where the identifier thing is never referenced elsewhere in this module. Tree shaking will remove this import, and remove the ~/thing module if also not used elsewhere. If, by some reason, you need this module to be imported for side effects only, you can change this import statement to:

import "~/thing";

And the module will remain a dependency. Alternative you can use the identifier in some where. Here we set it to a property on the window, making it a global:

import thing from "~/thing";

window.APP = { thing };

As globals can lead to implicit dependencies, it's better to avoid this.

**Comment by frank-dspeed** [comment]
@matthewp my old suggestion was wrong i now see the fail the fail is we import some thing that exports nothing look exactly at his code its not a global that gets treeshaken away he did not export anything so there is nothing

@PieterSwitten  this is expected result!

**Comment by matthewp** [comment]
Ok, so there is a similar test, however the test exports a function. Once I removed the export the test no longer works. So I was able to recreate this. Now to figure out why...

**Comment by matthewp** [comment]
https://github.com/stealjs/steal-tools/pull/1081

**Comment by matthewp** [comment]
Fixed in https://github.com/stealjs/steal-tools/releases/tag/v2.0.6
