### ISSUE TITLE
Breaking API with patch version

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#260]
Hey you are breaking API with patch version,

 for example in 0.10.6 build result was just `bundles {Array}` and in 0.10.7 build result is: 
```
graph {buildGraph}
steal {steal}
loader {Loader}
bundles {Array}
```
like in current doc http://stealjs.com/docs/steal-tools.BuildResult.html

Think it is not correct thing to do in patch version, at least it broke things for us in production.

**Comment by matthewp** [comment]
Sorry about that, it was always documented as BuildResult, it was incorrect in 0.10.0-0.10.6.  Bundles are still available as `buildResult.bundles` or you can roll back to 0.10.6 if you don't want to update your code.  I assumed since no one noticed that it was broken (not a BuildResult) that no one would complain when I fixed it.

**Comment by whitecolor** [comment]
Ok. Thanks.
