### ISSUE TITLE
Production build with canjs and jquery dependencies doesn't work in Safari and bundled malformed

### ISSUE THREAD

**Issue by ekvilon** [stealjs/steal-tools#274]
My test application uses canjs and jquery including stache template. 
Test repo is https://github.com/ekvilon/steal-test. Just run ```npm i -g gulp```, ```bower i```, ```npm i``` and then you can build project with ```gulp prod``` and test in browser ```index-dist.html``` using ```gulp prod-connect```

* In Safari browser (I had tested on Windows in Safari 5.1.7, on iPad Air 2, Mac OS X) scripts don't work. In other browsers everything is working as expected.
I see unhandled rejections in console.
```
Failed to load resource: the server responded with a status of 404 (Not Found)
browser-sync-client.2.8.0.jsFailed to load resource: the server responded with a status of 404 (Not Found)
all.js:145Potentially unhandled rejection [7] Error loading "src/templates/hello/main.hbs!hbs" at <unknown>
Error loading "src/templates/hello/main.hbs!hbs" from "all" at http://localhost:8091/dists/all.js
Error loading "hbs" at http://localhost:8091/dists/hbs.js
Not Found: http://localhost:8091/dists/hbs.js (WARNING: non-Error used)
all.js:145Potentially unhandled rejection [8] Error loading "src/templates/hello/main.hbs!hbs" at <unknown>
Error loading "src/templates/hello/main.hbs!hbs" from "scripts/modules/hello" at http://localhost:8091/dists/scripts/modules/hello.js
Error loading "hbs" at http://localhost:8091/dists/hbs.js
Not Found: http://localhost:8091/dists/hbs.js (WARNING: non-Error used)
```
When I add steal configuration on a page everything is okay.
```
steal.config({
  ext: {
    hbs: 'can/view/stache/system'
  }
});
```
* Two jquery files is bundling to production build.
* I have to specify ```"jquery/jquery": "./bower_components/jquery/dist/jquery.js"``` to paths section of system config in bower.json. Is it correct way to configure this?

**Comment by justinbmeyer** [comment]
I'm confused.  What error are you reporting?  That you have to add a config or something else?

**Comment by justinbmeyer** [comment]
Btw, it's convention to name your templates with `.stache`.  This is why you have to add the `hbs` config.

**Comment by isadovskiy** [comment]
@justinbmeyer, so we compiled the JS bundle and it work fine in FF, Chrome and IE. But not in Safari. In Safari we got a number of different issues, listed above. We will deploy the compiled example shortly.

We actually run into several issues: 

- two jQuery instances are bundled inside our JS file (one with 'jquery/jquery' alias and another one - with 'jquery'). In our actual app we are using 3-rd party pligins, which requires jQuery as 'jquery'. While Can requires jQuery using 'jquery/jquery'. As a result, jQuery got packed into JS two times. We was not able to find the correct way to work it around so asking about.

**Comment by isadovskiy** [comment]
Another issue with Safari is ext configuration with system plugins. Actually we have Handlebars templates, which we are going to re-use both on nodeJS back-end and in the browser as run-time Stache templates. So we would like to keep .hbs extension. Again, this weird issue happens just in Safari.

**Comment by isadovskiy** [comment]
The way we are trying to have everything up is Bower+StealJS+CanJS. However we did not find documentation how to configure this stack. So we also looking for advice - if our system config in bower.json is correct.

**Comment by justinbmeyer** [comment]
@matthewp please correct me if I'm wrong, but shouldn't their be a map of `jquery/jquery` to `jquery`?  That should hopefully fix your double jquery problem.

**Comment by isadovskiy** [comment]
> map jquery/jquery to jquery
We tried, but it did not work for us.

**Comment by ekvilon** [comment]
@justinbmeyer I just deployed sample to http://ekvilon.github.io/steal-test/. In Safari you should get errors in the console.

**Comment by matthewp** [comment]
you need a map and a paths.  map jquery/jquery to jquery and add a paths for jquery.

**Comment by matthewp** [comment]
I'm not sure [what this is about](https://github.com/ekvilon/steal-test/blob/master/Gulpfile.js#L17) but I bet it has a lot to do with your issues.  The build is meant to be a standalone thing, it creates a main bundle itself, you don't have to create one as well.

**Comment by ekvilon** [comment]
@matthewp Just did it as you adviced in other sample http://ekvilon.github.io/steal-test/index-fix.html.

**Comment by ekvilon** [comment]
In Safari is not working.

**Comment by ekvilon** [comment]
Used system config in bower.json:
```
  "system": {
    "paths": {
      "can/*": "./bower_components/canjs/steal/can/*.js",
      "jquery": "./bower_components/jquery/dist/jquery.js",
      "scripts/*": "./src/scripts/*.js"
    },
	"map": {
	  "jquery/jquery": "./bower_components/jquery/dist/jquery"
	},
    "ext": {
      "hbs": "can/view/stache/system"
    },
    "buildConfig": {
      "map": {
        "can/util/util": "can/util/domless/domless"
      }
    }
  }
```

**Comment by isadovskiy** [comment]
So our initial expectation also was the config about should work and we originally tried to configure steal in this way. However it causes 2 issues in *specifically* Safari: 

1. Adding "map" section above causes "Error loading "jquery/jquery" from "all" at http://ekvilon.github.io/steal-test/dists/all.js" error

2. Having custom "ext" in system config: "Error loading "src/templates/hello/main.hbs!hbs" from "all" at http://ekvilon.github.io/steal-test/dists/all.js"

To work this around we removed "map" section (and got jquery bundled twice in build). and also manually call "steal.config({ext: ....})" to work around second issue.

Again, both weird issues happens just in Safari (on Mac, PC and iOS).

**Comment by ekvilon** [comment]
Samples were updated and refactored to visualize troubles better.

**Comment by isadovskiy** [comment]
@matthewp, please let us know if you were able to reproduce the issue in Safari.

1. http://ekvilon.github.io/steal-test/index.html There are two issues here: 
 - Safari ignores ext: {hbs: 'can/view/stache/system'} section from bower.json and it causes http://take.ms/QTLUl
 - jQuery is included twice

2. http://ekvilon.github.io/steal-test/index-fix.html This is the try to eliminate the issue with duplicated jQuery inclusion with suggested by you fix (map: {'jquery/jquery': 'jquery'}). It cases more errors in Sarafi (it can't find jquery anymore): http://take.ms/sVKV3

**Comment by isadovskiy** [comment]
BTW, just noticed one thing. If I reset Safari's cache, everything works fine. But on all subsequent refreshes it fails with errors I mentioned above.

**Comment by matthewp** [comment]
Hey, really sorry to hear you guys are having issues.  I sent a PR to your repo showing the build working.  Never [do this](https://github.com/ekvilon/steal-test/blob/master/src/index-dist.html#L15) in a production file.  It will attempt to load that part before the rest of your app is really ready.

**Comment by isadovskiy** [comment]
Thanks for the reply, @matthewp. however what we actually building is site, not SPA. So we do not have single (main) entry point actually.

All we have is a number of modules (blocks) composed the page. They are added to page dunamically on BE. So basically every module is drovven by its own can.Control instance. And they are also configured from the page.

It means, we can not use main="src/scripts/main" in script tag. Instead, we bundle all individual controls together with stealJS into single file and load it in production. Since it's in <head>, I expect everything within the JS file is being registered inside steal. Then, in <body> I just want to request necessary control from steal and instantiate to control the specific block/module.

So again, I have multiple entry points within HTML file (like multiple applications are bundled within some JS). So wondering why this way we are using steal is not accurate? and what's the accurate way to achieve that we need?

You said, this part from body can be executed before the rest of my app is actually ready. But all my app is bundled together with stealjs and loaded in head. So wondering when all dependencies from bundled file are ready so I could require them?

**Comment by matthewp** [comment]
You can use `steal.import('modules')` in place of `steal('modules')`. It returns a promise.

However, steal-tools has a multi-app build for just this purpose. It will build sites that have multiple apps in a way that dependencies are shared between each page. This is explained [here](http://stealjs.com/docs/steal-tools.build.html#section_Multi_pageuse).

**Comment by isadovskiy** [comment]
Thank's for the advice, @matthewp. However still not clear how it could be helpful in our case..

Lets say, we have two independent modules: `modules/module1` and `modules/modules2`. They are expected to appear on the same page so i'm bundling them into all.js. 

Now I want to load all.js on my page, import the modules from and instantiate them in necessary places on HTML page.

So i still need to invoke something like 

steal.import('modules/module1').then (function (module) {
    module('#module1div');
});

However I need to make sure all.js is loaded and defines all its modules within steal before invoking the expression above.

The only thing which comes to mind is import all.js first. And then request specific module from. something like:

steal.import('dist/bundles/all.js').then (function () {
    steal.import('modules/module1').then (function (module) {
        module('#module1div');
    });
});

But it does not looks like a correct way to handle this. Could you suggest?

**Comment by isadovskiy** [comment]
I also looking at the all.js and I just see a list of `define (moduleId, dependencies, callback)` calls. So looks like all this calls should take place synchronously once bundled JS file is loaded. So wondering, why steal.import() called from <body> can't find defined module? Since looks like they all are defined in sync way...

**Comment by matthewp** [comment]
Your different pages have different entry points, right?  You should be able to build like this:

```js
stealTools.build({
  main: ["page1", "page2"],
  ...
});
```

And then in your page1 index.html do:

```html
<script src="steal.production.js" main="page1"></script>
```

**Comment by isadovskiy** [comment]
Well, not exactly. We have multiple mains within the same page. Basically, we can have multiple entry points within the same page - each one for the completely independent module, which all works separately and knows nothing about each other.

Like multiple applications on the same page, which should be launched separately. But we want to bundle them together since they will be on the same page.

**Comment by matthewp** [comment]
Ok, so create a module which just imports all of those:

### main.js
```js
steal("moduleA", "moduleB",function(){});
```

Can't you do it this way?

**Comment by isadovskiy** [comment]
We can do it. It will produce single bundle file contained all modules. 

Now we need to obtain necessary module from the bundle to instantiate it. How to do it? We could need multiple instances of the different modules from the bundle on the page. And they all should be instantiated inline in HTML.

**Comment by matthewp** [comment]
> Now we need to obtain necessary module from the bundle to instantiate it. How to do it? 

I don't understand, why can't you instantiate them in the `main.js` I just suggested you create?

> And they all should be instantiated inline in HTML.

Why?  You can instantiate use `steal.import` as I suggested before if you really want, but I don't understand the reason why they need to be instantiated in HTML and not in a JavaScript main.

**Comment by isadovskiy** [comment]
The issue is about our architecture. HTML page is assembled on server from the number of the available modules. Each module should be included into the page one or many times - depends on server. It's HTML piece + script (can.Control) which should wrap/work with this piece of HTML.

So we don't know ahead how many instantiations we will need so can't put them into main. And modules are rather small to load them individually. So we prefer to bundle them into single JS file and then obtain from somehow. And this is the exact our issue.

**Comment by matthewp** [comment]
Ok, in that case replace this:

```js
steal('scripts/modules/hello.js', function (Hello) {
  new Hello('body');
});
```

with this:

```js
steal.import('scripts/modules/hello').then(function (Hello) {
  new Hello('body');
});
```

**Comment by isadovskiy** [comment]
We tried but it fails in Safari.

**Comment by isadovskiy** [comment]
We tried, but it fails in Safari. 

However we bundled independent modules into single JS file in a little bit tricky way. We tried to make to automatic: scanned folders, found JS files and output define() statements for into temporary file, which contained dependencies of all modules we have. This is what our code did (https://github.com/matthewp/steal-test/commit/aa4453cb3e02bb4d28f18ab5b09c352244dc42d3). you wondered about this fs stuff initially. We just used define() syntax to build the dependencies for all modules (instead of steal() you suggested above). And then we tried steal.import() as you suggested. And it works in all browsers except Safari. So we started this tread here..

**Comment by matthewp** [comment]
Can you link to the code using steal.import?

**Comment by isadovskiy** [comment]
Will do and provide an example for you to review.

**Comment by isadovskiy** [comment]
@matthewp, sorry for the long silence. using `steal.import()` actually fixes all our issues. Sorry for bothering you for a so long time. I think this ticket should be closed.

Just one additional question. According to our workflow, we need to pack multiple individual independent modules into the single JS file. The amount of modules can vary and we just want to pack all JS files, which are under the specific folder structure.

At the moment we are traversing folder with custom JS code and generating temporary main file, referenced all found files. It's extra IO operation and we would like to avoid it. So would like to see such kind of bundling mode into Steal (similar to "include" option in RequireJS). "main" option will just accept the array of module names and there could be one additional option to not pack them into multiple optimized bundles, but create single JS bundle instead with all dependencies listed. If you think it makes sense, I'll create a separate ticket for.

Again, thanks for your help and great work on great tool!

**Comment by matthewp** [comment]
Cool, glad it worked out. if you could create a new issue about this "include" option (i'm not familiar) we can discuss it there.  Your workflow is a bit different from what we do.
