### ISSUE TITLE
Plugin load do not go though fetch in node

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#335]
If i'm correct when loading pluign module steal-tools seem just to readFile from fs, to unifiy behaviour with browser it would be right to apply the same set of import stages.

**Comment by matthewp** [comment]
It should absolutely be going through fetch. Can you provide a breaking example?

**Comment by whitecolor** [comment]
Well, while build, in one of the plugins (which loads first) I patch `System.fetch`:

Os I load `module1!plugin1`, and in plugin1.js I patch `System.fetch`
```javascirpt
var oldFetch = System.fetch;

System.fetch = function(load) {
    console.log('System.fetch name', load.name, 'address', load.address)
    return oldFetch.call(this, load)
}
```
After this other modules with other plugins do load. And pugins itself do not go thought this patched version (though modules it self do).

Then other modules like `module2!plugin2`, `module3!plugin2` do load, and they go though patched version, but `plugin2.js` do not it is just tried to be read from file system 

I even patch `fs.readFile` in `plugin1`:
```javascirpt
if (typeof window === 'undefined'){
    var fs = require('fs')
    var oldReadFile = fs.readFile;
    fs.readFile = function(address){
       console.log('fs.readFile', address)
       return oldReadFile.apply(fs, arguments)
    }
}
```
and plugin2.js do go though it.

**Comment by matthewp** [comment]
There are multiple loaders during a build, if you want to patch fetch you need to do it for both of them. The best way to get the loader that is loading your code is to use:

```js
var loader = require("@loader");

loader.fetch = ...
```

Rather than `System`. `@loader` will be whichever loader is loading that piece of code (for plugins it's the plugin loader.  

If you want to interrupt fetch for both I think you'll need to override `loader.fetch` and also `loader.localLoader.fetch` to get both loaders.

But if you're going to override the hooks It's probably better to do so in a extension rather than a plugin. [Here's a simple example](https://github.com/stealjs/steal-env/blob/master/env.js#L7) of one, notice that it adds itself to the `_extensions` array. This means the extension will be applied to both loaders in the build (or any other loader that is cloned).  You can do the same thing and add your extension to `configDependencies`.

**Comment by whitecolor** [comment]
Ok it seem to be totally fine if to use `@loader` on client and in node build.
