### ISSUE TITLE
import {some} from 'module'

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#352]
Is this syntax unsupported
```javascript
import {makeDOMDriver} from '@cycle/dom';
// makeDOMDriver is undefined
```

Though this works:
```javascript
import CycleDOM from '@cycle/dom';
const {makeDOMDriver} = CycleDOM
// makeDOMDriver is ok
```

because of babel5, not babel6? Or its a bug?

This relates to `steal` of cource, not `steal-tools`.

**Comment by matthewp** [comment]
No, that syntax is supported. That module only has a single export: https://github.com/cyclejs/cycle-dom/blob/master/src/cycle-dom.js#L122  

I believe `import {something} from 'foo'` only works when importing from an es6 module, not from a commonjs module. CJS only export the "default" export.

**Comment by daffl** [comment]
In Babel 6 on Node `import { something } from 'module';` with a module like

```js
module.exports = { something: 'test' };
```

does work.

**Comment by matthewp** [comment]
That's interesting, does the default case work as well?

**Comment by whitecolor** [comment]
`imoport {x, y} from 'module'` does not work with:
```
export default {
  x: 1,
  y: 2
}
```
works with:
```javascript
export var x = 1
export var y = 2
```

```javascript
module.export {
  x: 1,
  y: 2
}
```

**Comment by matthewp** [comment]
It's steal's responsibility.

```
export default {
  x: 1,
  y: 2
}
```

should not work, this is the default export. When you do `import {x} from 'module'` you are asking for the `x` export, but there is no x export. There's only a default export.

**Comment by whitecolor** [comment]
We are talkig about CJS.
```javascript
module.export = {
  x: 1,
  y: 2
}
```
It has alwasy actually only one export, and a lot of code codue using this, if this shouldn't work why is babel doing this so?

**Comment by whitecolor** [comment]
Shoul this me moved to steal issue?

**Comment by matthewp** [comment]
How ES6 will interoperate with CommonJS is still undecided.  Babel has changed what they exported a couple of times. I believe in Babel 6 it no longer exports a module.exports property but instead only exports `exports["default"]`.  I'm not sure, I have a hard time keeping up. Ultimately Node will decide how they interoperate when ES6 syntax lands in Node because they'll have to support both for a while.

> Shoul this me moved to steal issue?

Sure, if you have a suggestion about how it should interop today, that would be the place.
