### ISSUE TITLE
bundleSteal env is by default: development

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-tools#419]
if you make a build and set the option `bundleSteal=true` and load your app like `<script src="dist/bundles/testapp/main.js" main="testapp/main"></script>`, the env by default is "window-development" which is wrong.

**Comment by matthewp** [comment]
So, you might be thinking of adding something like:

```js
steal.env = "window-production";
```

While that probably works and is probably ok... I don't love the idea because it prevents us from using the bundled file somewhere other than in a web-browser (like running on a server).

Maybe instead we could add an option like: `steal.stealBundled = true` to the bundled file and then the same way we check for `steal.production` we could check for this property.  Here: https://github.com/stealjs/steal/blob/master/src/config.js#L232

**Comment by pYr0x** [comment]
@matthewp i like that way with `steal.stealBundled = true` ...

do we need that also if steal is bundled ?
https://github.com/stealjs/steal/blob/master/src/config.js#L230
i think we can leave setting `stealPath()` and the whole `paths` configs. or do i miss something?

**Comment by matthewp** [comment]
I think that might be ok. Try it out and let me know what happens.

**Comment by pYr0x** [comment]
https://github.com/stealjs/steal-tools/pull/425
