### ISSUE TITLE
Invalid order of styles after build

### ISSUE THREAD

**Issue by Krakabek** [stealjs/steal-tools#467]
Here is small example
https://github.com/Krakabek/StealStylesBug
All styles are in one file: styles.less
After building (node build.js) you can find index.css in dist folder
You can see, that body,input{font-family:"Helvetica Neue"... goes before reset block, containing font:inherit
Since order is critical in css files, produced app will have font:inherit in body

**Comment by matthewp** [comment]
Thanks, will take a look.

**Comment by justinbmeyer** [comment]
@matthewp my guess is that it's a bug with 2.4.0.

**Comment by matthewp** [comment]
What is 2.4.0?

**Comment by matthewp** [comment]
I'm assuming it's the minifier, going to create a smaller example.

**Comment by matthewp** [comment]
Recreated in this gist: https://gist.github.com/matthewp/4390cacb5adcb0bf320fb7ef8222a599

You can clone that, `npm install` and see the problem.  If you run:

```
npm run build
```

The problem exists.  if you run:

```
npm run build-no-minify
```

It works. So I think the problem is our css minifier.  I would start by trying to upgrade that, and see what it does.

**Comment by pYr0x** [comment]
closed #486 

@Krakabek can you confirm?

**Comment by Krakabek** [comment]
@pYr0x yup, using no-minify fixes that, thanks

**Comment by pYr0x** [comment]
@Krakabek i mean using `steal-tools beta`. with this beta version minify also should output the right order
