### ISSUE TITLE
css @import will be removed by clean-css

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-tools#487]
if you have a stylesheet like:

**bar.css**

```
@import url("foo.css");
```

Make a build with minification, `clean-css` remove the `@import` statement. but does not include the **foo.css**. 

**solutions**
- set `processImport` default to `false` in `cleanCSSOptions`. the `@import` statement will not be touched. but you have also to set `bundleAssets` to `true`
- try to make import rules working with `clean-css`. maybe we have to set some options e.g. `root`

@matthewp what solution do you prefer

**Comment by matthewp** [comment]
I think option 2 is the way to go.

**Comment by pYr0x** [comment]
i have a css file __base.css__
within i have a import
```
@import url("foo.css");
```

__foo.css__ is a sibling to __base.css__.
after build with steal-tools the url of the import is rewritten `@import url(../../../src/foo.css);` because i dont have set `bundleAssets` to `true`.
__but where does this url rewriting happen?__ i didnt find it

**Comment by matthewp** [comment]
In the CSS plugin itself I believe.

**Comment by pYr0x** [comment]
i added a `console.log` to https://github.com/stealjs/steal-css/blob/master/css.js#L21-L70
but this never gets called during build process

**Comment by matthewp** [comment]
Yeah, you're right, I think it's done here: https://github.com/stealjs/steal-tools/blob/master/lib/bundle/normalize_source.js

**Comment by pYr0x** [comment]
i made a couple of changes and add some tests. but i stumble on some problems.

classic `@import` works fine with clean-css

but if we have a image in the imported file, this image-url does not rewritten by steal. because this source does not goes through steal anymore.

i am helpless, because if we have to write a complex css tracer and import files recursive and watch out for import loops.

**Comment by m-mujica** [comment]
## My findings so far: 

**clean-css@4 does not inline remote `@import` anymore [only local](https://github.com/jakubpawlowicz/clean-css#important-40-breaking-changes)**

steal-tool is swallowing clean-css errors; the sync call [here](https://github.com/stealjs/steal-tools/blob/31b8d1b27908bc5957b37d4ebf8677f3d35f746f/lib/buildTypes/minifyCSS.js#L13) does not throw but populates an errors array in the result object.

I added the following check locally 

```javascript
if (result.errors && result.errors.length) {
  throw new Error(result.errors[0]);
}
```

and now my build fails with:

```
Potentially unhandled rejection [2] Error: Ignoring local @import of "../../../p.css" as resource is missing.
```

Preventing steal-tools to rewrite the `@import` urls (normalize source) fixes my build and clean-css inlines the styles just fine. But remote `@import` won't work because we need to use clean-css's [async version](https://github.com/jakubpawlowicz/clean-css#how-to-process-remote-imports-correctly).

## My plan

Use the promise-based [clean-css interface](https://github.com/jakubpawlowicz/clean-css#promise-interface) and refactor around [here](https://github.com/stealjs/steal-tools/blob/31b8d1b27908bc5957b37d4ebf8677f3d35f746f/lib/bundle/write_bundles.js#L31) to handle the new async behavior; this should take care of error propagation and the async nature of remote `@import` - the user has to [turn off the flag though](https://github.com/jakubpawlowicz/clean-css#inlining-options)

steal-tools will use clean-css default and only inline local imports.

Hopefully this does not break the `@import "locate://";` syntax.

cc: @matthewp @pYr0x

**Comment by pYr0x** [comment]
Hey Manuel, it has been a while.
Do you have a demo or a test that show the current behavior and shows what's wrong while building.. ? 
What is the current result and what should be the result...
Thx a lot
