### ISSUE TITLE
Minification breaks CJS dependency detection

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal-tools#563]
when my module is minified, the letter used in the CJS factory function for `require` is the same letter used later on in the same code to call a different function.

![screen shot 2016-11-25 at 16 33 12](https://cloud.githubusercontent.com/assets/724877/20634738/d1b29dce-b332-11e6-94c7-707d20671c7d.png)

![screen shot 2016-11-25 at 16 32 57](https://cloud.githubusercontent.com/assets/724877/20634743/d71cb4c0-b332-11e6-97b6-c117073744b3.png)

when I try to load the app locally, steal throws with a 404 loading "glob", which shouldn't be a dependency.

I'll fix this by preventing UglifyJS to mangle `require`

**Comment by m-mujica** [comment]
I confirmed this by adding a build script to my app and setting the following option:

```javascript
stealTools.build(config, {
  mangle: {
    except: ['require']
  }
});
```

that fixed the problem 💥

**Comment by m-mujica** [comment]
https://github.com/systemjs/systemjs/issues/1417#issuecomment-244943853

**Comment by matthewp** [comment]
lodash is not hit with this bug (I think), so I think it should move up in priority.

**Comment by matthewp** [comment]
Here's an example repo demonstrating the bug: https://github.com/DesignByOnyx/steal-lodash-bug

This is a particularly nasty one. I tried using `mangle: { reserved: ["require"] }` so that the `require` function is not renamed. However it still breaks because this code:

```js
var memoizeCapped = require('./_memoizeCapped');

/** Used to match property names within property paths. */
var reLeadingDot = /^\./,
    rePropName = /[^.[\]]+|\[(?:(-?\d+(?:\.\d+)?)|(["'])((?:(?!\2)[^\\]|\\.)*?)\2)\]|(?=(?:\.|\[\])(?:\.|\[\]|$))/g;
```

Gets reordered to look like:

```js
var reLeadingDot = /^\./,
    rePropName = /[^.[\]]+|\[(?:(-?\d+(?:\.\d+)?)|(["'])((?:(?!\2)[^\\]|\\.)*?)\2)\]|(?=(?:\.|\[\])(?:\.|\[\]|$))/g,
   memoizeCapped = require('./_memoizeCapped');
```

And because of the reordering, Steal's commonjs detection doesn't recognize the require() call as a dependency (because there is code to exclude `require` when inside of a string, and that regex breaks the string detection).

Strangely, if you turn off minification and do minification manually from the command-line, this reordering doesn't occur, and everything works.

Suggestions:

1. We always include `{ mangle: { reserved: ["require"] } }` so that the `require` functions are not renamed. This should fix *most* occurrences of this bug, I think.
2. If we only minify at the bundle level and not at the module level, presumably we should get the same output as what happened when I did minification manually. However some spot-checking and that doesn't seem to be the case. Investigate why if we turn off module-level minification why the output is different vs. doing minification from the commandline `uglifyjs` command. Is there some default options that exist in the commandline but not from the js API, perhaps? 

This is just a start, a really hard bug to solve.

**Comment by m-mujica** [comment]
@matthewp I tried running the CLI but I see the vars being reordered and the `require` being pushed after the regexes.

Maybe you were using a different uglifyjs version?

Looking at the options available, maybe we can turn that optimization off. 

```
./node_modules/uglify-es/bin/uglifyjs public/dist/bundles/steal-lodash-bug/public/index.js --compress -m reserved=[require] -o public/dist/bundles/steal-lodash-bug/public/index.js
```

**Comment by matthewp** [comment]
I was using the `node_modules/.bin/uglifyjs` which I think is the same as what you showed there. Not sure why I got a different result, I can try again later.

I looked to see if there was any documentation about the reordering but couldn't find any.

**Comment by m-mujica** [comment]
@matthewp it's not really re-ordering variables, it's inlining the require call,

```js
var n = /^\./
      , r = /[^.[\]]+|\[(?:(-?\d+(?:\.\d+)?)|(["'])((?:(?!\2)[^\\]|\\.)*?)\2)\]|(?=(?:\.|\[\])(?:\.|\[\]|$))/g;
    var a = /\\(\\)?/g;
    var o = require("./_memoizeCapped")(function(e) {
```

I tried turning off the option to join vars and inline "simple" function, but that does not fix it... Still doing some research, maybe we need to "fix" the deps regex :|

**Comment by matthewp** [comment]
it's not the deps regex, there's a regex that detects strings, and anything inside of a string it ignores. It thinks that `r` regex is the beginning of a string section, and that the `require` is inside of a string. I stepped through that code. Fixing the string regexp might be possible but damned hard.

**Comment by DesignByOnyx** [comment]
I'm a bit of a glutton for regex - so if you want to offload that onto somebody ;)

**Comment by m-mujica** [comment]
@DesignByOnyx  this is the regex that's supposed to match strings with their content:

```
var stringRegEx = /("[^"\\\n\r]*(\\.[^"\\\n\r]*)*"|'[^'\\\n\r]*(\\.[^'\\\n\r]*)*')/g;
```

so, in theory for the following code 

```js
var r = /"/g,var o = require("foo")
```

The only match should be `"foo"` but, as you can see in the screenshot below, it "thinks" the string starts with the `"` inside the regexp all the way up to the first one inside the require call.

![screen shot 2017-07-19 at 16 11 39](https://user-images.githubusercontent.com/724877/28391933-25ee2d80-6c9d-11e7-8de7-d2ad5603b957.png)

In dev code, it's less likely to happen since there would probably be a new line before each variable name in the declaration. 

Thoughts?

**Comment by m-mujica** [comment]
@James0x57 might also have some input here 👾

**Comment by James0x57** [comment]
@m-mujica 
This should fix it:
```js
var stringRegEx = /(([`"'/])((\\\2|[^\\\2\r\n])+?)\2)/g;
```

![image](https://user-images.githubusercontent.com/7545075/28426825-f1dfc268-6d39-11e7-9136-5b6ff6c05be0.png)

`stringRegEx` is used to make sure the call to require isn't inside of one of those matches. Technically it's not just matching strings any more because it's also matching regexes. But that'll do it.

Note: Template strings are a problem in very rare case currently. This helps with that a little but they will still be a problem if they span multiple lines.

**Comment by DesignByOnyx** [comment]
This  works - but I feel like we need more test cases. All I did was put `[^\/]` at the beginning, outside of any capturing groups. So the string is still in the first capturing group:

```
[^\/]("[^"\\\n\r]*(\\.[^"\\\n\r]*)*"|'[^'\\\n\r]*(\\.[^'\\\n\r]*)*')
```
![image](https://user-images.githubusercontent.com/514040/28427711-55d748a0-6d34-11e7-8680-51382bd9db3f.png)

**Comment by James0x57** [comment]
Implementation is complete, waiting on this to be merged:
https://github.com/stealjs/steal/pull/1249
