### ISSUE TITLE
multimain build fail

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-tools#602]
i created a sample app.
https://github.com/pYr0x/steal-multimain

the build fails with this error
```
Potentially unhandled rejection [1] TypeError: Cannot read property 'name' of undefined
    at /Users/julian/PhpstormProjects/steal-multimain/node_modules/steal-tools/lib/bundle/make_bundle_name_map.js:6:13
    at Array.forEach (native)
```

the problem seems to be, that:
`main2.js` requires `main1.js`, but both are multi main entry points

```
stealTools.build({
	main: [
		"steal-multimain/main1",
		"steal-multimain/main2"
	],
	config: __dirname+"/package.json!npm"
},{
	minify: false,
	debug: true
});
```

**Comment by m-mujica** [comment]
@matthewp when the graph is generated using `main1` as THE main, the graph looks more or less like this:

```javascript
{
  "multi-main-dep@1.0.0#main1": {
    "load": {},
    "deps": [],
    "dependencies": [],
    "bundles": [
      "multi-main-dep@1.0.0#main1"
    ]
  }
}
```

then the graph generated using `main2` looks like: 

```javascript
{
  "multi-main-dep@1.0.0#main2": {
    "load": {},
    "deps": [
      "./main1"
    ],
    "dependencies": [
      "multi-main-dep@1.0.0#main1"
    ]
  },
  "multi-main-dep@1.0.0#main1": {
    "load": {},
    "deps": [],
    "dependencies": []
  }
}
```

the function that merges the graphs, adds the bundle "main2" to "main1" here. https://github.com/stealjs/steal-tools/blob/master/lib/graph/make_graph_with_bundles.js#L46

The node with name `multi-main-dep@1.0.0#main1` is found in both graphs and we end up adding the second "main" bundle as a bundle of `multi-main-dep@1.0.0#main1`.

I think the problem is there, but I'm trying to wrap my head around that logic. 
What's that `addBundle` trying to do there? or why is it even needed?

**Comment by matthewp** [comment]
The purpose of `addBundle` is to keep track of every bundle that a module belongs to. If there's modules:

```js
// bundle-a.js
require('./module-a');
```

```js
// bundle-b.js
require('./module-a');
```

Then _module-a_ belongs to the _bundle-a_ and _bundle-b_ bundles. This information is used to split modules into bundles. If module-a only belonged to bundle-b it would go into the bundle-b bundle. But since it belongs to both it **might** get split into a shared bundle, bundle-a-b, or it **might** be put into one of the bundles (the code splitting algorithm determines this based on depth and bundle size).

**Comment by matthewp** [comment]
One solution might be to check in addBundle if the module is one of the `main` modules. If it is, don't add a second 'bundles' to it.

**Comment by m-mujica** [comment]
I tried that yesterday but it was not working for some reason.... trying to figure out why now.
