### ISSUE TITLE
Watch mode detecting changes but not refreshing bundles

### ISSUE THREAD

**Issue by kylegifford** [stealjs/steal-tools#706]
We configured watch mode on our build. It seemed to be detecting changes to both JS and Stache files, but when reloading the app or checking the bundles, the changes did not appear.

**Comment by matthewp** [comment]
Hey @kylegifford, I wasn't able to replicate this problem. I created a gist to try: https://gist.github.com/matthewp/566c1f7913c4ed005f3d86940b79cef1#file-view-stache

It works the way that I saw you using it. If you edit the view.stache (which is part of a bundle) it is able to rebuild this file.

Closing for now, if you can remove some of your code to figure out what scenario is causing it to break I can reopen and investigate more.

Created #707 and #708 because of the defaults not working properly.
