### ISSUE TITLE
Circular dependencies in slim builds

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#742]
We should figure out if this is something that works with webpack, and regardless see if this is something that can be added.  If it adds code (more than a couple of lines) it should be something that is added conditionally only when needed.

**Comment by m-mujica** [comment]
@matthewp would you like me to take a look at this for phase 2? or should I work on the node support next?

**Comment by matthewp** [comment]
This is fine, whatever you want to do first. Maybe hold off on Node as we will want to talk about it again so we have our use-cases covered well.

**Comment by m-mujica** [comment]
@matthewp my example with circular dependencies throws on runtime with webpack

```js
// foo.js
var bar = require("./bar");

module.exports = function() {
  console.log("foo");
  bar();
};

// bar.js
var foo = require("./foo");

module.exports = function() {
  console.log("bar");
  foo();
};

// app.js
var foo = require("./foo");
foo();
```

![screen shot 2017-06-30 at 07 13 56](https://user-images.githubusercontent.com/724877/27736996-bcbff584-5d63-11e7-81d6-3823dc126e7d.png)

I'm going to run the same example with ours but I'm confident the same will happen..... I'm going to look into detecting circular deps in steal-tools and maybe throw an error.

**Comment by matthewp** [comment]
Ok, we do want to support it whether webpack does or not. But yeah, for a first step, for the 1.4.0 release having a check that lets the user know it's not currently supported is fine.

**Comment by m-mujica** [comment]
Since the slim output works in a CJS-like fashion, to get circular deps working we're going to make sure the module exports are declared before the imports (transpile), this way such exports are guaranteed to be accessible in the bodies of importing modules [See http://2ality.com/2014/09/es6-modules-final.html#cyclic-dependencies-in-commonjs]

I did manually the change in a circular deps slim output and it worked but I found an issue in the loader require es6 module imports. Currently the loader will always return `.default` if the `__esModule` flag is found, and that breaks named imports :/
