### ISSUE TITLE
can-import not working with optimize build

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-tools#861]
i make a build  with `optimize`.
i have a stache file that import a component 
```
<can-import from="~/components/content/">
            {{#if isResolved}}
                <x-content vm:app:from="../this" vm:page:from="page"></x-content>

            {{else}}
                Loading...
            {{/if}}
        </can-import>
```
the component is bundled with `optimize` but never loaded progressive.
i only added the `main` to my script-tags like
`<script src="/dist/bundles/steal-pwa-example/index.js" async></script>`
i thought, slim-loader will progressive load the component?

here is a example app
https://github.com/pYr0x/steal-pwa-example/tree/new-steal-tool

the problem is: https://github.com/canjs/can-util/blob/master/js/import/import.js#L27

**Comment by m-mujica** [comment]
### Known issues

- [ ] a) **Add optimized build support to `can-util/import/import`**

Replace [this](https://github.com/canjs/can-util/blob/50b02fc2646b0a9c14f86452cf0cfcf0fd4aff0e/js/import/import.js#L38-L39) with:
```js
try {
  steal
    .import(moduleName, {
      name: parentName
    })
    .then(resolve, reject);
} catch (e) {
  // ideally this will use can.getObject
  resolve();
}
```

> How does this fix the issue? 

During the optimize build, steal-tools will replace calls to `steal.import` (and `System.import`) for 
`stealRequire.dynamic`; `stealRequire` is injected to the optimized function factory and this way the bundle is imported

- [ ] a.1) **Make done-autorender register dynamic ids for the optimized loader**

The optimized loader relies on runtime configuration to map the authored module identifiers to the numeric bundle/module ids used in the optimized output. 

Unfortunately, when `can-import` is used, `loader.bundle` gets the normalized bundle name but `System.import` gets the name before normalize. 

There is a mechanism in steal-tools to deal with this, the `loader` has a `slimConfig` object that extensions can use to register things like ids that should be mapped on runtime. 

Around [here](https://github.com/donejs/autorender/blob/f3b081378391d8ab102c78f56e38b45f07ccd46a/src/init.js#L56) make sure `done-autorender` registers the dynamic imports:

```js
if (loader.slimConfig) {
  var toMap = loader.slimConfig.toMap;
  var res = getIntermediateAndImports(load.source);

  Array.prototype.push.apply(toMap, res.imports);
  Array.prototype.push.apply(toMap, res.dynamicImports);
}
```
> I wonder if it'd make more sense to hide the `slimConfig` properties and expose methods in the loader itself, or maybe get rid of the property altogether and add stuff to `load.metada`. 

- [ ] a.1.1) **Make sure steal-tools can locate the dynamic ids during build.**

The previous change won't work unless steal-tools maps the module id to a numeric id, since the normalized bundle names are set to `loader.bundle`, the nodes in graph will use the normalized name, too.

So, around [here](https://github.com/stealjs/steal-tools/blob/master/lib/stream/convert_slim_config.js#L28-L30), we should try normalizing if `graph[id]` is missing before throwing. (`converSlimConfig` shoud be async)

```js
return new Promise(function(resolve) {
  // if we are going to normalize theses ids we should know get
  // the parent module too
  var idsToBeMapped = config.toMap.map(function(id) {
    return loader.normalize(id).then(function(name) {
      map[id] = getSlimId(name);
    });
  });

  Promise.all(idsToBeMapped).then(function() {
    // mutates the slimConfig property!
    loader.slimConfig = assign({}, omit(config, ["toMap"]), {
      map: map,
      extensions: config.extensions.map(getSlimId)
    });

    resolve(data);
  });
});
```

- [ ] a.2) **Make the optimized loader aware that main bundle modules are loaded already**

One issue introduced by `can-import` is that it dynamically loads modules that might be already bundled in the main bundle. So [this object](https://github.com/stealjs/steal-tools/blob/20407b37c44ee2c6769c422bbbdf075f273b0f5e/lib/node/slim/progressive_loader_partial.js#L74) should be prepopulated (with the main bundle id) when the (optimized) loader is part of main. 

With that in place, `stealRequire.dynamic` will treat modules in main bundle [as already loaded](https://github.com/stealjs/steal-tools/blob/20407b37c44ee2c6769c422bbbdf075f273b0f5e/lib/node/slim/progressive_loader_partial.js#L117-L119) (because they are :D)

- [ ] b) **[`systemImportZone`](https://github.com/donejs/autorender/blob/master/src/template.txt#L20-L34) is not transpiled correctly.**

`transpile` only replace `steal.import` when it's used in a function call, it needs to be replaced in this case too, otherwise dynamic import won't be catched by the zone.

- [ ] c) **Attach `onScriptLoad` to the script tag onload/onerror callbacks**  

Around [here](https://github.com/stealjs/steal-tools/blob/20407b37c44ee2c6769c422bbbdf075f273b0f5e/lib/node/slim/progressive_loader_partial.js#L144) do:

```js
script.onload = script.onerror = onScriptLoad;
```

**Comment by m-mujica** [comment]
## Need help (or lots of time)

After applying the changes mentioned before locally, I noticed my example app does not render correctly. 

I was able to locate the source of the problem but I don't understand why it happens.

The loader [sets a timeout](https://github.com/stealjs/steal-tools/blob/20407b37c44ee2c6769c422bbbdf075f273b0f5e/lib/node/slim/progressive_loader_partial.js#L144) in case the script tag takes too long to load. 


Then [clears it](https://github.com/stealjs/steal-tools/blob/20407b37c44ee2c6769c422bbbdf075f273b0f5e/lib/node/slim/progressive_loader_partial.js#L149) when the load callback is called.

For some reason `Zone.current` is null when `clearTimeout` is called and the `Zone` where the app renders never resolves.

**Comment by pYr0x** [comment]
is this issue completely solved? or did some issues you comment still exist?

**Comment by m-mujica** [comment]
There are some pull requests still open, I'm going to take care of those today and I'll close this issue once everything is merged/released.

**Comment by m-mujica** [comment]
The example app I used to replicate this is working now with the latest releases. 

Closing this one 🎉
