### ISSUE TITLE
Can't build successfully without transpiling Async/Await

### ISSUE THREAD

**Issue by BigAB** [stealjs/steal-tools#961]
So, what I want is a React app, that uses Async/Await, but I don't want to transpile async/await stuff (but do want jsx, decorators, and class-properties) because the support matrix will only include browsers that support async/await and the bundles get huge fast when transpiling async/await.

Here is a project to clone and see the problems:
https://gist.github.com/BigAB/e55df65b4715a8830fd48e8a93a32adb

I tried a couple of different things you can see in the package.json `scripts`.

- The App seems to work as expected in **dev** mode
- Trying to use `steal-tools` cli commands to build (`npm run steal-build`) ends up with an app error:
`steal.production.js:11 ReferenceError: regeneratorRuntime is not defined`
- Trying to use the lower level way of overwriting the `transpile` function in steal-tools build config  (`npm run build`), as seen in `build.js` ends up throwing an error at build time `Cannot read property 'length' of undefined`
- using the babel cli directly (`npm run babel`) seems to create the file I would want (with out the module loading though)

...So, what am I doing wrong, why can't I seem to NOT compile async/await? Is there a better way to get what I want?

**Comment by matthewp** [comment]
Think the problem is here: https://github.com/stealjs/transpile/commit/ddd922401a14ad19b6793b7868a4500b2eef3bff

@m-mujica Do you remember if we meant to do this (this means es2015 is always included)... I think maybe this was a mistake.

If so we just need to do `opts.presets = opts.presets || defaultPresets` I think.

I tried that locally but it broke because esprima wasn't able to parse the javascript, probably just need to update esprima.

**Comment by matthewp** [comment]
https://github.com/stealjs/transpile/pull/134 is a PR for that. @m-mujica if you have time to review that one I would appreciate it.

**Comment by matthewp** [comment]
This was fixed.
